### PR TITLE
Fix ISO8601 compatible timestamp format on maven package

### PR DESCRIPTION
**Pull request by sergio-alonso**
```
$ mvn package

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:07.577s
[INFO] Finished at: Wed Dec 21 19:21:12 CET 2016
[INFO] Final Memory: 69M/247M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project server-service: There are test failures.

$ mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-105-lowlatency", arch: "amd64", family: "unix"

$ cat server/service/target/surefire-reports/com.torodb.standalone.ToroDbBootstrapServiceTest.txt

------------------------------------------------------------------------------
Test set: com.torodb.standalone.ToroDbBootstrapServiceTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 9.739 sec <<< FAILURE! - in com.torodb.standalone.ToroDbBootstrapServiceTest
testCreateStampedeService(com.torodb.standalone.ToroDbBootstrapServiceTest)  Time elapsed: 9.287 sec  <<< ERROR!
com.google.inject.CreationException:
Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.RuntimeException: buildTimestamp property not in ISO8601 format
at com.torodb.packaging.DefaultBuildProperties.<init>(DefaultBuildProperties.java:60)
at com.torodb.packaging.DefaultBuildProperties.class(DefaultBuildProperties.java:39)
while locating com.torodb.packaging.DefaultBuildProperties
at com.torodb.standalone.BootstrapModule.configure(BootstrapModule.java:74)
while locating com.torodb.core.BuildProperties

Caused by: java.time.format.DateTimeParseException: Text '2016-12-21T19:18:05+0100' could not be parsed at index 19
at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
at java.time.Instant.parse(Instant.java:395)
at com.torodb.packaging.DefaultBuildProperties.<init>(DefaultBuildProperties.java:83)
```

### CODE REVIEW

**Comment by gortiz** [comment]
Hi @sergio-alonso,

Thanks for your contribution. Unfortunately (or maybe fortunately?) this bug has been solved on devel branch!

**Comment by sergio-alonso** [comment]
Hi @gortiz,

I have the same issue on devel branch.

**Comment by gortiz** [comment]
Which maven version are you using? We previously had that problem when we used maven.build.timestamp.format ended with Z. We changed to X because it is ISO 8601 according to the [javadoc](http://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html).

**Comment by sergio-alonso** [comment]
I'm going to update maven and check it again.

Because this is what I have running now:

```
$ mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-105-lowlatency", arch: "amd64", family: "unix"
```

I have checked several formats with Maven 3.0.5 and result is the same build failure:

```
<maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ssZZ</maven.build.timestamp.format>
Caused by: java.time.format.DateTimeParseException: Text '2016-12-22T11:22:34+0100' could not be parsed at index 19

<maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ssZ</maven.build.timestamp.format>
Caused by: java.time.format.DateTimeParseException: Text '2016-12-22T11:19:05+0100' could not be parsed at index 19

<maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ssXX</maven.build.timestamp.format>
Caused by: java.time.format.DateTimeParseException: Text '2016-12-22T11:13:05+0100' could not be parsed at index 19

<maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ssX</maven.build.timestamp.format>
Caused by: java.time.format.DateTimeParseException: Text '2016-12-22T11:09:28+01' could not be parsed at index 19

<maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ss'X'</maven.build.timestamp.format>
Caused by: java.time.format.DateTimeParseException: Text '2016-12-22T11:03:39X' could not be parsed at index 19
```

It seems that is only working with format described in [maven documentation](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#Available_Variables) as default value:

`<maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ss'Z'</maven.build.timestamp.format>`

**Comment by gortiz** [comment]
You should upgrade your maven version. It is 3.3.x right now! In fact Maven should complain about that, because the root pom has 3.2.2 as prerequisite!

**Comment by sergio-alonso** [comment]
All is working as expected using the right maven version.

Thanks @gortiz, and sorry for my mistake.

**Comment by gortiz** [comment]
No problem! I am glad to help! Thanks for your interest on ToroDB!

**Pull request closed without merging**
